language: java
jdk: oraclejdk8
script: mvn install -DskipTests=true -B -V
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/03c7c9da65e5622a948c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false